#!/usr/bin/env sh

source ssh.cfg
echo Test connection
test=$(sshpass -p $pwd ssh $usr@$domain "echo connected")
if [ "$test" != connected ]; then
    echo Cannot connect to host
    exit 1
fi
echo Connection success
echo Making directories
sshpass -p $pwd ssh $usr@$domain "mkdir $serverDir/public; mkdir $serverDir/public/$topic; mkdir $serverDir/public/$topic/$version" 
echo Sending file from $src/app/build/outputs/apk/tinkerPatch/debug/patch_signed_7zip.apk to $usr@$domain:$serverDir/public/$topic/$version 
sshpass -p $pwd scp $src/app/build/outputs/apk/tinkerPatch/debug/patch_signed_7zip.apk $usr@$domain:$serverDir/public/$topic/$version && success=true
if [ "$success" = true ]; then
    echo Send file success 
    sshpass -p $pwd ssh $usr@$domain "node $serverDir/patch_process/update.js"
else
    echo Send file failed
fi
